apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  JWT_SECRET: "PRFT_SUPER_SECRET_KEY_2024"
  DB_PASSWORD: "secure_password_123"
  REDIS_PASSWORD: "redis_secure_pass"